---
- name: Copy
  hosts: Windows
  become: false
  gather_facts: false
  vars:
    source: "/home/user/Documents/Ansible"
    destination: "Desktop/"
  tasks:
   - name: copy ping
     ansible.windows.win_copy:
       src: "{{ source }}"
       dest: "{{ destination }}"


